---
name: Test
"on":
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test on Go ${{ matrix.go }}
    permissions:
      checks: write
      contents: read
      pull-requests: read
      statuses: write
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        go: ["1.25", "1.24", "1.23", "1.22"]
        include:
          - go: "1.25"
            go-version: "1.25.0-rc.1"
          - go: "1.24"
            go-version: "1.24.4"
            update-coverage: true
          - go: "1.23"
            go-version: "1.23.10"
          - go: "1.22"
            go-version: "1.22.12"
    env:
      GOTOOLCHAIN: local
    steps:
      - name: ✔ Check out
        uses: actions/checkout@v4
      - name: 🐹 Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: 🧸 golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
      - name: 🔨 Test
        run: go test -race -coverprofile=cover.out ./...
      - name: 🧑🏻‍💻 codecov
        uses: codecov/codecov-action@v5
        if: ${{ matrix.update-coverage }}
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
